// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCESGR-RGdl-nIF2hwzG8Bc3lNfDmoEGso',
    appId: '1:931564903992:web:84790c1108a53654cbd0cd',
    messagingSenderId: '931564903992',
    projectId: 'costasplit-ce2fb',
    authDomain: 'costasplit-ce2fb.firebaseapp.com',
    storageBucket: 'costasplit-ce2fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_xcvTHVHdWXdddCATD6T-C64WdqqI9P4',
    appId: '1:931564903992:android:7eb1f9d2bdcc8cefcbd0cd',
    messagingSenderId: '931564903992',
    projectId: 'costasplit-ce2fb',
    storageBucket: 'costasplit-ce2fb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCESGR-RGdl-nIF2hwzG8Bc3lNfDmoEGso',
    appId: '1:931564903992:web:014e4a5f8fdabcc2cbd0cd',
    messagingSenderId: '931564903992',
    projectId: 'costasplit-ce2fb',
    authDomain: 'costasplit-ce2fb.firebaseapp.com',
    storageBucket: 'costasplit-ce2fb.firebasestorage.app',
  );
}
